dist: trusty
sudo: true
services:
- docker
language: node_js
node_js:
- '7.5'
install:
- npm install
before_script:
- DOCKER_IMAGE_NAME="q-editor"
- DOCKER_TAG=$TRAVIS_BRANCH
script:
- cd client && npm install && jspm install && gulp export && cd ..;
- docker build -t $DOCKER_IMAGE_NAME:$DOCKER_TAG .;
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"; docker tag $DOCKER_IMAGE_NAME:$DOCKER_TAG
  nzzonline/$DOCKER_IMAGE_NAME:$DOCKER_TAG; docker push nzzonline/$DOCKER_IMAGE_NAME:$DOCKER_TAG;
- if [ $TRAVIS_BRANCH == "staging" ] && [ $TRAVIS_PULL_REQUEST == "false" ]; then docker run --rm -it -e RANCHER_URL -e
  CATTLE_ACCESS_KEY -e CATTLE_SECRET_KEY etlweather/gaucho upgrade $RANCHER_SERVICE_ID_STAGING
  --auto_complete --start_first --imageUuid="docker:nzzonline/$DOCKER_IMAGE_NAME:$DOCKER_TAG" || true;
  fi
