version: 2

references:
  container_config: &container_config
    docker:
      - image: circleci/node:9

jobs:
  build:
    <<: *container_config

    working_directory: ~/repo

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
      - run: npm install
      - run: cd client && npm install && node_modules/jspm/jspm.js install && node_modules/gulp/bin/gulp.js lint && node_modules/gulp/bin/gulp.js export && cd ..;
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  build-docker:
    <<: *container_config
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
      - run: npm install
      - run: cd client && npm install && node_modules/jspm/jspm.js install && node_modules/gulp/bin/gulp.js lint && node_modules/gulp/bin/gulp.js export && cd ..;
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          TAG=$CIRCLE_BRANCH
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker build -t q-editor:$TAG .
          docker tag q-editor:$TAG nzzonline/q-editor:$TAG
          docker push nzzonline/q-editor:$TAG

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - build-docker:
          requires:
            - build