version: 2

references:
  container_config: &container_config
    docker:
      - image: circleci/node:8

jobs:
  build:
    <<: *container_config

    working_directory: ~/repo

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  test:
    <<: *container_config
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
      - run: npm install
      - run: npm run test

  build-docker:
    <<: *container_config
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
      - run: npm install
      - run: npm run test
      - run: docker build -t nzzdev/q-editor:$CIRCLE_BRANCH
      - run: docker push nzzdev/q-editor:$CIRCLE_BRANCH

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - build-docker:
          requires:
            - test
      - push-docker:
          requires:
            - build-docker
