version: 2

references:
  container_config: &container_config
    docker:
      - image: circleci/node:8

jobs:
  build:
    <<: *container_config

    working_directory: ~/repo

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
      - run: npm install
      - run: npm install -g jspm
      - run: cd client && npm install && jspm install && gulp lint && gulp export && cd ..;
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  build-docker:
    <<: *container_config
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
      - run: npm install
      - run: npm install -g jspm
      - run: cd client && npm install && jspm install && gulp lint && gulp export && cd ..;
      - setup_remote_docker:
          docker_layer_caching: true
      - run: docker build -t nzzdev/q-editor:$CIRCLE_BRANCH .
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker push nzzdev/q-editor:$CIRCLE_BRANCH

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - build-docker:
          requires:
            - build
